//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.28 at 08:58:21 AM AEDT 
//


package com.ibm.dfdljaxb.gdmgen;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="GDMDef">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="source_schema" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="source_message" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="source_parser" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="target_schema" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="target_message" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="target_parser" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="FieldMapping" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="source_field" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="target_field" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="base_action" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="assign_value" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "gdmDef",
    "fieldMapping"
})
@XmlRootElement(name = "IOMapModelMetaCSV")
public class IOMapModelMetaCSV {

    @XmlElement(name = "GDMDef", required = true)
    protected IOMapModelMetaCSV.GDMDef gdmDef;
    @XmlElement(name = "FieldMapping", required = true)
    protected List<IOMapModelMetaCSV.FieldMapping> fieldMapping;

    /**
     * Gets the value of the gdmDef property.
     * 
     * @return
     *     possible object is
     *     {@link IOMapModelMetaCSV.GDMDef }
     *     
     */
    public IOMapModelMetaCSV.GDMDef getGDMDef() {
        return gdmDef;
    }

    /**
     * Sets the value of the gdmDef property.
     * 
     * @param value
     *     allowed object is
     *     {@link IOMapModelMetaCSV.GDMDef }
     *     
     */
    public void setGDMDef(IOMapModelMetaCSV.GDMDef value) {
        this.gdmDef = value;
    }

    /**
     * Gets the value of the fieldMapping property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fieldMapping property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFieldMapping().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IOMapModelMetaCSV.FieldMapping }
     * 
     * 
     */
    public List<IOMapModelMetaCSV.FieldMapping> getFieldMapping() {
        if (fieldMapping == null) {
            fieldMapping = new ArrayList<IOMapModelMetaCSV.FieldMapping>();
        }
        return this.fieldMapping;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="source_field" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="target_field" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="base_action" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="assign_value" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "sourceField",
        "targetField",
        "baseAction",
        "assignValue",
        "description"
    })
    public static class FieldMapping {

        @XmlElement(name = "source_field", required = true)
        protected String sourceField;
        @XmlElement(name = "target_field", required = true)
        protected String targetField;
        @XmlElement(name = "base_action", required = true)
        protected String baseAction;
        @XmlElement(name = "assign_value")
        protected String assignValue;
        protected String description;

        /**
         * Gets the value of the sourceField property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSourceField() {
            return sourceField;
        }

        /**
         * Sets the value of the sourceField property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSourceField(String value) {
            this.sourceField = value;
        }

        /**
         * Gets the value of the targetField property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTargetField() {
            return targetField;
        }

        /**
         * Sets the value of the targetField property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTargetField(String value) {
            this.targetField = value;
        }

        /**
         * Gets the value of the baseAction property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBaseAction() {
            return baseAction;
        }

        /**
         * Sets the value of the baseAction property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBaseAction(String value) {
            this.baseAction = value;
        }

        /**
         * Gets the value of the assignValue property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAssignValue() {
            return assignValue;
        }

        /**
         * Sets the value of the assignValue property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAssignValue(String value) {
            this.assignValue = value;
        }

        /**
         * Gets the value of the description property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDescription() {
            return description;
        }

        /**
         * Sets the value of the description property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDescription(String value) {
            this.description = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="source_schema" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="source_message" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="source_parser" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="target_schema" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="target_message" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="target_parser" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "sourceSchema",
        "sourceMessage",
        "sourceParser",
        "targetSchema",
        "targetMessage",
        "targetParser"
    })
    public static class GDMDef {

        @XmlElement(name = "source_schema", required = true)
        protected String sourceSchema;
        @XmlElement(name = "source_message", required = true)
        protected String sourceMessage;
        @XmlElement(name = "source_parser", required = true)
        protected String sourceParser;
        @XmlElement(name = "target_schema", required = true)
        protected String targetSchema;
        @XmlElement(name = "target_message", required = true)
        protected String targetMessage;
        @XmlElement(name = "target_parser", required = true)
        protected String targetParser;

        /**
         * Gets the value of the sourceSchema property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSourceSchema() {
            return sourceSchema;
        }

        /**
         * Sets the value of the sourceSchema property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSourceSchema(String value) {
            this.sourceSchema = value;
        }

        /**
         * Gets the value of the sourceMessage property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSourceMessage() {
            return sourceMessage;
        }

        /**
         * Sets the value of the sourceMessage property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSourceMessage(String value) {
            this.sourceMessage = value;
        }

        /**
         * Gets the value of the sourceParser property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSourceParser() {
            return sourceParser;
        }

        /**
         * Sets the value of the sourceParser property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSourceParser(String value) {
            this.sourceParser = value;
        }

        /**
         * Gets the value of the targetSchema property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTargetSchema() {
            return targetSchema;
        }

        /**
         * Sets the value of the targetSchema property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTargetSchema(String value) {
            this.targetSchema = value;
        }

        /**
         * Gets the value of the targetMessage property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTargetMessage() {
            return targetMessage;
        }

        /**
         * Sets the value of the targetMessage property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTargetMessage(String value) {
            this.targetMessage = value;
        }

        /**
         * Gets the value of the targetParser property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTargetParser() {
            return targetParser;
        }

        /**
         * Sets the value of the targetParser property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTargetParser(String value) {
            this.targetParser = value;
        }

    }

}
