//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.19 at 02:49:12 PM AEST 
//


package com.ibm.wesbBO;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.ibm.com/xmlns/prod/websphere/wbiserver/map/6.0.0}name"/>
 *         &lt;element ref="{http://www.ibm.com/xmlns/prod/websphere/wbiserver/map/6.0.0}inputBusinessObjectVariable"/>
 *         &lt;element ref="{http://www.ibm.com/xmlns/prod/websphere/wbiserver/map/6.0.0}outputBusinessObjectVariable"/>
 *         &lt;element ref="{http://www.ibm.com/xmlns/prod/websphere/wbiserver/map/6.0.0}propertyMap" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="targetNamespace" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "name",
    "inputBusinessObjectVariable",
    "outputBusinessObjectVariable",
    "propertyMap"
})
@XmlRootElement(name = "businessObjectMap", namespace = "http://www.ibm.com/xmlns/prod/websphere/wbiserver/map/6.0.0")
public class BusinessObjectMap {

    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected InputBusinessObjectVariable inputBusinessObjectVariable;
    @XmlElement(required = true)
    protected OutputBusinessObjectVariable outputBusinessObjectVariable;
    @XmlElement(required = true)
    protected List<PropertyMap> propertyMap;
    @XmlAttribute(name = "targetNamespace")
    protected String targetNamespace;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the inputBusinessObjectVariable property.
     * 
     * @return
     *     possible object is
     *     {@link InputBusinessObjectVariable }
     *     
     */
    public InputBusinessObjectVariable getInputBusinessObjectVariable() {
        return inputBusinessObjectVariable;
    }

    /**
     * Sets the value of the inputBusinessObjectVariable property.
     * 
     * @param value
     *     allowed object is
     *     {@link InputBusinessObjectVariable }
     *     
     */
    public void setInputBusinessObjectVariable(InputBusinessObjectVariable value) {
        this.inputBusinessObjectVariable = value;
    }

    /**
     * Gets the value of the outputBusinessObjectVariable property.
     * 
     * @return
     *     possible object is
     *     {@link OutputBusinessObjectVariable }
     *     
     */
    public OutputBusinessObjectVariable getOutputBusinessObjectVariable() {
        return outputBusinessObjectVariable;
    }

    /**
     * Sets the value of the outputBusinessObjectVariable property.
     * 
     * @param value
     *     allowed object is
     *     {@link OutputBusinessObjectVariable }
     *     
     */
    public void setOutputBusinessObjectVariable(OutputBusinessObjectVariable value) {
        this.outputBusinessObjectVariable = value;
    }

    /**
     * Gets the value of the propertyMap property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the propertyMap property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPropertyMap().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PropertyMap }
     * 
     * 
     */
    public List<PropertyMap> getPropertyMap() {
        if (propertyMap == null) {
            propertyMap = new ArrayList<PropertyMap>();
        }
        return this.propertyMap;
    }

    /**
     * Gets the value of the targetNamespace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTargetNamespace() {
        return targetNamespace;
    }

    /**
     * Sets the value of the targetNamespace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTargetNamespace(String value) {
        this.targetNamespace = value;
    }

}
