//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.19 at 02:49:12 PM AEST 
//


package com.ibm.wesbBO;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ibm.wesbBO package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _JavaCode_QNAME = new QName("http://www.ibm.com/xmlns/prod/websphere/wbiserver/map/6.0.0", "javaCode");
    private final static QName _Name_QNAME = new QName("http://www.ibm.com/xmlns/prod/websphere/wbiserver/map/6.0.0", "name");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ibm.wesbBO
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Input }
     * 
     */
    public Input createInput() {
        return new Input();
    }

    /**
     * Create an instance of {@link InputBusinessObjectVariable }
     * 
     */
    public InputBusinessObjectVariable createInputBusinessObjectVariable() {
        return new InputBusinessObjectVariable();
    }

    /**
     * Create an instance of {@link PropertyMap }
     * 
     */
    public PropertyMap createPropertyMap() {
        return new PropertyMap();
    }

    /**
     * Create an instance of {@link CustomAssignment }
     * 
     */
    public CustomAssignment createCustomAssignment() {
        return new CustomAssignment();
    }

    /**
     * Create an instance of {@link Output }
     * 
     */
    public Output createOutput() {
        return new Output();
    }

    /**
     * Create an instance of {@link Move }
     * 
     */
    public Move createMove() {
        return new Move();
    }

    /**
     * Create an instance of {@link OutputBusinessObjectVariable }
     * 
     */
    public OutputBusinessObjectVariable createOutputBusinessObjectVariable() {
        return new OutputBusinessObjectVariable();
    }

    /**
     * Create an instance of {@link BusinessObjectMap }
     * 
     */
    public BusinessObjectMap createBusinessObjectMap() {
        return new BusinessObjectMap();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ibm.com/xmlns/prod/websphere/wbiserver/map/6.0.0", name = "javaCode")
    public JAXBElement<String> createJavaCode(String value) {
        return new JAXBElement<String>(_JavaCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ibm.com/xmlns/prod/websphere/wbiserver/map/6.0.0", name = "name")
    public JAXBElement<String> createName(String value) {
        return new JAXBElement<String>(_Name_QNAME, String.class, null, value);
    }

}
